// import 'typeface-black-ops-one'
// import 'typeface-anton'
// import 'typeface-catamaran'
// import 'typeface-changa-one'
// import 'typeface-titan-one'
// import 'typeface-bowlby-one'
// import 'typeface-k2d'
// import 'typeface-bungee-inline'
import '@fontsource/bungee-inline'
import '@fontsource/righteous'
import '@fontsource/fredoka-one'
import '@fontsource/rampart-one'
import '@fontsource/archivo-black'
import '@fontsource/black-ops-one'
import '@fontsource/palette-mosaic'
import '@fontsource/saira-stencil-one'
import '@fontsource/shanti'
import '@fontsource/port-lligat-sans'
import '@fontsource/mukta-mahee'
import '@fontsource/baloo-chettan-2'
import "./src/pages/tailwind.css"