import 'typeface-black-ops-one'
import 'typeface-anton'
import 'typeface-catamaran'
import 'typeface-changa-one'
import 'typeface-titan-one'
import 'typeface-bowlby-one'
import 'typeface-k2d'
import 'typeface-bungee-inline'
// import '@fontsource/bungee-inline'
import "./src/pages/tailwind.css"